name: all-contributors

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    #         ┌───────────── minute (0 - 59)
    #         │ ┌───────────── hour (0 - 23)
    #         │ │ ┌───────────── day of the month (1 - 31)
    #         │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         │ │ │ │ │
    #         │ │ │ │ │
    #         │ │ │ │ │
    - cron: '* 0 * * *'
  workflow_dispatch:

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SRE_BOT_TOKEN }}

      - name: Update README.md
        uses: milvus-io/hero-bot@dco-enabled
        with:
          # Required
          token: ${{ secrets.SRE_BOT_TOKEN }}
          repos: 'milvus-io/milvus.io'
          targetFile: 'README.md'
          # Optional
          isAscend: True
          width: '30px'
          workingDir: '/home/runner/work/milvus.io/milvus.io'
