name: Build and deploy to preview

on:
  repository_dispatch:
    types: prod-deploy
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: update submodules
        run: |
          git submodule init
          git submodule update --remote

      - name: build site
        run: |
          yarn install
          yarn build

      - name: Sync files
        run: |
          echo ${{ secrets.RSYNC_PASSWORD }} > rsync.pass
          sudo chmod 600 rsync.pass
          sudo chown root rsync.pass
          sudo rsync --password-file=rsync.pass -rDvpzc --delete public/ rsync://${{secrets.PROD_SITE}}
