name: Build npm package docker for master branch

on:
  push:
    branches:
      - master
      
jobs:
  # Build npm package docker
  buildnpm:
    runs-on: ubuntu-latest
    # output if package.json is updated
    outputs:
      packagejson: ${{ steps.changesfiles.outputs.packagejson }}
    steps:
      - name: Checkout Code  
        run: |
          cd ..
          sudo git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          cd www.milvus.io
          sudo chmod 777 -R .
          sudo git checkout ${GITHUB_REF##*/}
        
      - name: Get changed files
        id: changesfiles
        run: |
          echo "::set-output name=packagejson::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep package.json$ | xargs)"   
      
      - name: Login to DockerHub
        if: needs.buildnpm.outputs.packagejson == 'package.json'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}
          
      - name: Build and push
        if: needs.buildnpm.outputs.packagejson == 'package.json'
        run: |
          docker build -t milvusdb/milvus.io.builder:${GITHUB_REF##*/} -f ./NPMDOCKER .
          docker push milvusdb/milvus.io.builder:${GITHUB_REF##*/}
