name: Build and deploy to preview

on:
  repository_dispatch:
    types: dev-deploy
  push:
    branches:
      - preview
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Install OpenVPN and kubectl
        run: |
          sudo apt-get update
          sudo apt-get install openvpn -y

      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          FILE_OVPN: '.github/workflows/client.ovpn'
        env:
          CA_CRT: ${{ secrets.VPN_CA}}
          USER_CRT: ${{ secrets.VPN_CRT }}
          USER_KEY: ${{ secrets.VPN_KEY }}

      - name: update submodules
        run: |
          git submodule init
          git submodule update --remote

      - name: build site
        run: |
          yarn install
          yarn build

      - name: Sync files
        run: |
          echo ${{ secrets.RSYNC_PASSWORD }} > rsync.pass
          sudo chmod 600 rsync.pass
          sudo chown root rsync.pass
          sudo rsync --password-file=rsync.pass -rDvpzc --delete public/ rsync://milvusio@a1202fdac6c7d488ba400d2b01203056-1949499790.us-west-2.elb.amazonaws.com/milvusio
