name: Build and deploy to preview

on:
  repository_dispatch:
    types: dev-deploy
  push:
    branches:
      - preview
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: update submodules
      run: |
        git submodule init
        git submodule update --remote

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://zilliz.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_19b2bf4e76ed4da5979091a842d3fd2d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fcdf52b41adf4d978d72b00dbf9f4165 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: zilliz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0106db9abf8a481291d42e2e124070d5 }}/milvuspreview2021:${{ github.sha }}
        file: ./Preview.Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'milvus-io-production'
        slot-name: 'dev'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fa1b3ab4f557439ca4cb7a2f63c50d3e }}
        images: 'zilliz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0106db9abf8a481291d42e2e124070d5 }}/milvuspreview2021:${{ github.sha }}'
