name: Trigger from web-content docs to update submodule (prod)

on:
  repository_dispatch:
    types: prod-deploy
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: update submodules
        run: |
          git submodule init
          git submodule update --remote
          git add .
          git commit -m 'update submodule'
          git push origin master
